services:
  xbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xarr-xbot
    restart: unless-stopped
    
    # 环境变量（如果需要）
    environment:
      - TZ=Asia/Shanghai
    
    # 挂载卷，持久化配置和数据
    volumes:
      - ./config:/app/config:ro          # 配置文件只读
      - ./logs:/app/logs                  # 日志目录
      - ./data:/app/data                  # 数据存储目录
    
